### ISSUE TITLE
Mcb inactive

### ISSUE THREAD

**Issue by Noople** [trendwerk/multiple-content-blocks#75] opened 2016-05-04 13:48 UTC
hi there

i do work with a new version of wordpress 4.5.1 and multiple content blocks. when i edit a content in admin and switch from my main language to another language the block will be inactive. i tried to solve this in the settings without any success. could you please help me how to fix this bug. thanks a lot!

kind regards.
thomas hess

**Comment by haroldangenent** [comment] 2016-05-04 14:31
MCB doesn't do anything with languages. What do you mean exactly?

Could you give me soms steps to reproduce this on a clean WordPress install?

**Comment by Noople** [comment] 2016-05-04 19:47
Hi, as soon as I edit content in another language (I use wpml plugin) the mcb goes inactive for the additional languages (mcb for main language stays active). It has worked properly for two years. It's a new bug since wp update 4.5.1 Thanks for your support!

Kind regards.
Thomas Hess

**Comment by haroldangenent** [comment] 2016-05-12 11:56
Hi Thomas,

I'm sorry, but I cannot assist you with this. I'm not familiar with WPML and this plugin is not designed to work with it persé. This plugin however just uses a WordPress function (`wp_editor()`), which could be supported by WPML by default. Therefore, this is more probably a WPML issue. However, I am not sure.

I'd advice you to use [Advanced Custom Fields](https://www.advancedcustomfields.com/), that may support WPML out of the box.

I'll have to close this issue, since it's not specifically a bug for this plugin.

Regards,
Harold

**Closed by haroldangenent** 2016-05-12 11:56 UTC

**Comment by Noople** [comment] 2016-05-12 12:06
Hi Harold

Thanks for your answer!

I'll give ACS a try.

Kind regards.
Thomas Hess

­­—————————
Thomas Hess
Mediengestalter

Noople
Bäckerstrasse 54
8004 Zürich

+41 76 337 99 88
kontakt@noople.ch
www.noople.ch

2016-05-12 13:56 GMT+02:00 Harold Angenent <notifications@github.com>:
